services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - piscinenet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    networks:
      - piscinenet


volumes:
  pgdata:
  pgadmin-data:


networks:
  piscinenet:
    driver: bridge
