version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:                     # ← this should align with 'environment', NOT be inside it
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - piscinenet

volumes:
  pgdata:

networks:
  piscinenet:
    driver: bridge
